---
- name: Playbook to create custom EE
  hosts: "{{ _host | default('controller') }}"
  gather_facts: false
  vars_files:
    - vars/execution_environments.yml
  roles:
    - infra.ee_utilities.ee_builder
...