---
- name: Playbook to create custom EE
  hosts: "{{ _host | default('controller') }}"
  gather_facts: false

  vars_files:
    - vars/execution_environments.yml

  tasks:
    - name: Install ansible-builder
      ansible.builtin.pip:
        name: ansible-builder
        state: present

    - name: Build EEs
      ansible.builtin.include_role:
        name: infra.ee_utilities.ee_builder
...